spring:
  application:
    name: ac-control-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ac_control}
    username: ${DB_USERNAME:alena}
    password: ${DB_PASSWORD:alena}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: ${YANDEX_CLIENT_ID:0c998c76f8c5456e8564501a65de828a}
            client-secret: ${YANDEX_CLIENT_SECRET:your-client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: " http://localhost:3000/oauth/callback"
            scope: login:email, login:info
            client-name: Yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: login

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:ac-control-256-bit-secret-key-for-development-only}
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

logging:
  level:
    root: INFO
    ru.itmo.accontrol: DEBUG
    org.springframework.security: DEBUG
